### ISSUE TITLE
Self hosted compiler and some suggestions

### ISSUE THREAD

**Issue by rishavs** [KeliLanguage/compiler#72]
Is self hosting planned for Keli compiler?

Also, can you add a roadmap of sorts (perhaps using Github projects, or trello, or just a bullet point list), so it is easier to follow the development of this language?

Finally, a section of what I can actually do right now with the language would be great. Can I only use it for Hello world like toy programs? Can I make a web server with it? Is the standard lib usable?
For me rust's arewegameyet.com, arewewebyet.com etc are fantastic for new users checking out the language. Not a full website, but just a section in the webpage about the current capabilities of the language for some popular uses cases would be great.

**Comment by wongjiahau** [comment]
Hi there @rishavs , thanks for the comments.

At the moment I don't plan to do self hosting on Keli, as I'm concerned about integration with JavaScript libraries. 

It's definitely a great idea to include the capabilities of Keli in a webpage, I just need to find time to do it. 

Are you interested in contributing to this language?

**Comment by rishavs** [comment]
Hey @wongjiahau 

I am not much of a programmer so I can't contribute in core dev work. But once I like a language/community I try to help out by writing docs, articles, bug reports etc.

I will keep an eye on keli because I agree with a lot of its core idea. Once the project is more mature and I can start using it in my toy projects, I can start contrubuting.

**Comment by wongjiahau** [comment]
@rishavs Thank you for showing interest in writing documentations, do you mind to suggest me what kind of library should Keli have first?

**Comment by rishavs** [comment]
Stdlib or external modules? 
You will almost always have a large number of users checking your project out if you have a web server? That seems to be the most popular use for new languages right now. Something like Elm-ish pattern would be great as well for people to build projects in a functional language.

**Comment by wongjiahau** [comment]
Thanks for the suggestion!
